[serve]
# The address to serve on
address = "127.0.0.1"
# The port to serve on
port = 8080
# Open a browser tab once the initial build is complete
open = false
# Disable auto-reload of the web app
no_autoreload = false
# Enable HTTPS
tls_key_path = "../backend/certificates/key.pem"
tls_cert_path = "../backend/certificates/cert.pem"
